services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  connection.mysql.promofarma:
    class: Doctrine\DBAL\Connection
    factory: 'Doctrine\DBAL\DriverManager::getConnection'
    arguments:
      $params:
        url: '%env(DATABASE_URL)%'
        driver: pdo_mysql
        charset: UTF8
